# Generated by Django 3.1.4 on 2020-12-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_ID', models.CharField(max_length=20, unique=True)),
                ('Member_NickName', models.CharField(max_length=20, unique=True)),
                ('Member_Mail', models.CharField(max_length=50, unique=True)),
                ('Member_Address', models.CharField(max_length=150)),
            ],
        ),
    ]
